### ISSUE TITLE
Grass disappears from specific angles 

### ISSUE THREAD

**Issue by SIsilicon** [Zylann/godot_heightmap_native_plugin#35]
I don't know why. But grass disappears when looked from certain angles. I don't what those angles are in particular... It's hard to explain. You need more info, just comment :/ Again it's pretty hard to explain.

**Comment by Zylann** [comment]
Yes, I'm aware of this issue, but haven't got to look for a fix yet. It's because the AABBs are wrong, they need to use a system similar to the one I used for the heightmap.

**Comment by Zylann** [comment]
I just pushed a few fixes for grass AABBs, let me know if it fixes your problem

**Comment by SIsilicon** [comment]
Yeah it seems so. Thank you. :)

**Comment by LKS90** [comment]
I was just playing around a bit and I still have that issue. I simply upped the AABB in the y-Dimension for a fix, but I barely know what I am doing. In [this ](https://github.com/Zylann/godot_heightmap_native_plugin/blob/master/addons/zylann.hterrain/detail/detail_renderer.gd#L273)line, I add the CHUNK_SIZE to the aabb.size.y before multiplying the result with the terrain_scale.y, but using the CHUNK_SIZE is not really based on any reasoning (I just needed some "big"ish number).

    aabb.size = Vector3(CHUNK_SIZE, (aabb.size.y + CHUNK_SIZE) * terrain_scale.y, CHUNK_SIZE)

My problem without my shitty fix is the grass at the bottom of the screen disappears with a shallow viewing angle. Depending on how the avatar is facing relative to the detail chunks, it sometimes results in a whole row of grass patches missing at the bottom of the screen or just some patches flickering in and out when turning. When I am close to the ground and look "up" (with the whole terrain visible in the bottom strip), I have a completely naked terrain.

**Comment by Zylann** [comment]
Is it getting worse if you do that on to of a tall mountain/ tall hill? (Aka far from "sea" level)

**Comment by LKS90** [comment]
Hey there! Sorry for the late reply. [Here ](https://imgur.com/a/wI3t4mE)is an album with example screenshots and the settings used for the terrain in [this](https://youtu.be/Vi1M5DtmSFI) video. The settings in the example screenshots were similar, it was definitely a base height of 0 as well.

**Comment by Zylann** [comment]
I think there is a bug with the generator. When I run it, normals are not updating properly, so maybe it's related to grass AABBs being wrong too...

**Comment by Zylann** [comment]
Indeed AABBs are wrong
![image](https://user-images.githubusercontent.com/1311555/43617140-31ef9402-96b8-11e8-8386-6add452ae7ba.png)

**Comment by Zylann** [comment]
Fixed in 881afdedbac20fa9937c1428e67c27da2213a4a5, let me know if it happens again
